version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "api-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-dumc1f21cn6m"
s3_prefix = "api-app"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
